# Generated by Django 4.2.7 on 2024-01-04 15:26

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_download_limit', models.PositiveSmallIntegerField(default=50, verbose_name='محدودیت دانلود روزانه')),
                ('envato_scraper_is_active', models.BooleanField(default=True, verbose_name='فعالیت ربات انواتو')),
                ('under_construction', models.BooleanField(default=False, verbose_name='در دست تعمیر')),
                ('error_description', models.TextField(blank=True, null=True, verbose_name='توضیح مشکل')),
            ],
            options={
                'verbose_name': 'تنظیم سرویس',
                'verbose_name_plural': 'تنظیمات سرویس',
            },
        ),
        migrations.CreateModel(
            name='CustomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='کلید')),
                ('message', models.TextField(blank=True, null=True, verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'پیام دلخواه',
                'verbose_name_plural': 'پیام های دلخواه',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('envato', 'envato')], default='envato', max_length=255, verbose_name='نوع فایل')),
                ('page_link', models.CharField(max_length=5000, verbose_name='لینک صفحه اصلی فایل')),
                ('unique_code', models.CharField(blank=True, max_length=5000, null=True, verbose_name='کد یکتا')),
                ('file_storage_link', models.CharField(blank=True, max_length=3000, null=True, verbose_name='لینک فضای ذخیره')),
                ('file', models.FileField(blank=True, max_length=1500, null=True, upload_to='files/', verbose_name='فایل')),
                ('download_percentage', models.PositiveSmallIntegerField(default=0, verbose_name='درصد تکمیل دانلود')),
                ('is_acceptable_file', models.BooleanField(default=True, verbose_name='آیا فایل با فرمت های طراحی شده سازگار است؟')),
                ('in_progress', models.BooleanField(default=False, verbose_name='آیا عملیات دانلود در حال اجراست؟')),
                ('failed_repeat', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش های ناموفق برای دانلود این فایل')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل ها',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text_id', models.CharField(max_length=255, verbose_name='link text id')),
                ('links', models.TextField(verbose_name='links')),
            ],
            options={
                'verbose_name': 'لینک تکست',
                'verbose_name_plural': 'لینک تکست',
            },
        ),
        migrations.CreateModel(
            name='TelegramBotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('bot_token', models.CharField(max_length=255, verbose_name='توکن')),
            ],
            options={
                'verbose_name': 'تنظیمات ربات تلگرام',
                'verbose_name_plural': 'تنظیمات ربات تلگرام',
            },
        ),
    ]
