# Generated by Django 4.2.7 on 2023-12-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_linktext'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_storage_link',
            field=models.CharField(default=1, max_length=3000, verbose_name='لینک فضای ذخیره'),
            preserve_default=False,
        ),
    ]
