# Generated by Django 4.2.7 on 2023-12-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_file_file_storage_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_storage_link',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='لینک فضای ذخیره'),
        ),
    ]
