
def name_cleaner(name):
    name = str(name)
    name = name.replace(' ', '-')
    name = name.replace('  ', '-')
    name = name.replace('   ', '-')
    name = name.replace('_', '-')
    name = name.replace('__', '-')
    name = name.replace('___', '-')
    name = name.replace('.', '-')
    name = name.replace('..', '-')
    name = name.replace('...', '-')
    name = name.replace("'", '-')
    name = name.replace("''", '-')
    name = name.replace("'''", '-')
    name = name.replace("/", '-')
    name = name.replace("//", '-')
    name = name.replace("///", '-')
    name = name.replace(":", '-')
    name = name.replace("::", '-')
    name = name.replace(":::", '-')
    name = name.replace("(", '-')
    name = name.replace("((", '-')
    name = name.replace("(((", '-')
    name = name.replace(")", '-')
    name = name.replace("))", '-')
    name = name.replace(")))", '-')
    name = name.replace("-", '-')
    name = name.replace("--", '-')
    name = name.replace("---", '-')
    name = name.replace("----", '-')
    name = name.replace("-----", '-')
    name = name.replace("------", '-')
    name = name.lower()
    latest_dot_index = name.rfind('-')
    name = name[:latest_dot_index] + '.' + name[latest_dot_index + 1:]
    return name
