# Generated by Django 4.2.7 on 2023-11-09 11:40

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('daily_count', models.PositiveSmallIntegerField(verbose_name='تعداد روزانه')),
                ('expiry_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ و زمان انقضا')),
            ],
            options={
                'verbose_name': 'توکن چند تایی',
                'verbose_name_plural': 'توکن های چند تایی',
            },
        ),
        migrations.CreateModel(
            name='RedeemDownloadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام توکن')),
                ('token_type', models.CharField(choices=[('single', 'single'), ('multiple', 'multiple')], default='single', max_length=255, verbose_name='نوع توکن')),
                ('token_unique_code', models.CharField(max_length=255, verbose_name='کد یکتا')),
                ('tokens_count', models.PositiveSmallIntegerField(verbose_name='تعداد')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('expiry_days', models.PositiveSmallIntegerField(verbose_name='تعداد روز انقضا پس از ردیم شدن')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
            ],
            options={
                'verbose_name': 'ردیم توکن دانلود',
                'verbose_name_plural': 'ردیم توکن های دانلود',
                'ordering': ['is_used'],
            },
        ),
        migrations.CreateModel(
            name='SingleToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('expiry_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ و زمان انقضا')),
            ],
            options={
                'verbose_name': 'توکن تکی',
                'verbose_name_plural': 'توکن های تکی',
            },
        ),
        migrations.AlterModelOptions(
            name='userredeemhistory',
            options={'ordering': ['user', '-created_at'], 'verbose_name': 'تاریخچه ردیم', 'verbose_name_plural': 'تاریخچه ردیم ها'},
        ),
        migrations.AddField(
            model_name='profile',
            name='multi_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.multitoken', verbose_name='توکن چند تایی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='single_tokens',
            field=models.ManyToManyField(blank=True, to='accounts.singletoken', verbose_name='توکن های تکی'),
        ),
        migrations.AlterField(
            model_name='userredeemhistory',
            name='redeemed_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.redeemdownloadtoken', verbose_name='توکن ردیم شده'),
        ),
        migrations.DeleteModel(
            name='DownloadToken',
        ),
    ]
