# Generated by Django 4.2.7 on 2023-11-09 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_multitoken_redeemdownloadtoken_singletoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درخواست')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.file', verbose_name='فایل درخواست شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه درخواست',
                'verbose_name_plural': 'تاریخچه درخواست ها',
                'ordering': ['-created_at'],
            },
        ),
    ]
