# Generated by Django 4.2.7 on 2023-11-09 12:44

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userfilehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequesthistory',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='userrequesthistory',
            name='telegram_message_id',
        ),
        migrations.CreateModel(
            name='UserRequestHistoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(editable=False, max_length=255, verbose_name='ایدی چت تلگرام')),
                ('telegram_message_id', models.CharField(editable=False, max_length=255, verbose_name='ایدی پیام تلگرام')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درخواست')),
                ('user_request_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_request_history_detail', to='accounts.userrequesthistory', verbose_name='تاریخچه درخواست کاربر')),
            ],
            options={
                'verbose_name': 'جزئیات تاریخچه درخواست',
                'verbose_name_plural': 'جزئیات تاریخچه درخواست ها',
            },
        ),
    ]
