# Generated by Django 4.2.7 on 2023-11-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0006_alter_userrequesthistory_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequesthistory',
            name='files',
            field=models.ManyToManyField(to='core.file', verbose_name='فایل های متصل به این درخواست'),
        ),
    ]
