# Generated by Django 4.2.7 on 2023-11-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userrequesthistory_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userredeemhistory',
            name='redeemed_token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_redeem_history_redeemed_token', to='accounts.redeemdownloadtoken', verbose_name='توکن ردیم شده'),
        ),
    ]
