# Generated by Django 4.2.7 on 2023-11-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userredeemhistory_redeemed_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daily_used',
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_used_total',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد کل موارد درخواست شده طی آخرین روز'),
        ),
        migrations.AddField(
            model_name='profile',
            name='multi_token_daily_used',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد موارد درخواست شده طی آخرین روز توسط توکن روزانه'),
        ),
    ]
