# Generated by Django 4.2.7 on 2023-11-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_daily_used_profile_daily_used_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redeemdownloadtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'ردیم توکن دانلود', 'verbose_name_plural': 'ردیم توکن های دانلود'},
        ),
        migrations.AddField(
            model_name='profile',
            name='user_latest_requested_files',
            field=models.TextField(blank=True, null=True, verbose_name='آخرین فایل های درخواستی کاربر'),
        ),
    ]
