# Generated by Django 4.2.7 on 2023-11-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0010_alter_redeemdownloadtoken_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfilehistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'تاریخچه فایل دریافتی کاربر', 'verbose_name_plural': 'تاریخچه فایل های دریافتی کاربر'},
        ),
        migrations.AddField(
            model_name='userrequesthistory',
            name='data_track',
            field=models.CharField(default=1, editable=False, max_length=1000, verbose_name='داده ها'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfilehistory',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.file', verbose_name='فایل دریافت شده'),
        ),
    ]
