# Generated by Django 4.2.7 on 2023-11-26 22:04

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userfilehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multitoken',
            name='daily_count',
            field=models.PositiveSmallIntegerField(editable=False, verbose_name='تعداد روزانه'),
        ),
        migrations.AlterField(
            model_name='multitoken',
            name='expiry_date',
            field=django_jalali.db.models.jDateTimeField(editable=False, verbose_name='تاریخ و زمان انقضا'),
        ),
        migrations.AlterField(
            model_name='multitoken',
            name='is_used',
            field=models.BooleanField(default=False, editable=False, verbose_name='استفاده شده'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_latest_requested_files',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='آخرین فایل های درخواستی کاربر'),
        ),
        migrations.AlterField(
            model_name='redeemdownloadtoken',
            name='expiry_days',
            field=models.PositiveSmallIntegerField(default=90, verbose_name='تعداد روز انقضا پس از ردیم شدن'),
        ),
        migrations.AlterField(
            model_name='redeemdownloadtoken',
            name='token_unique_code',
            field=models.CharField(editable=False, max_length=255, verbose_name='کد یکتا'),
        ),
        migrations.AlterField(
            model_name='redeemdownloadtoken',
            name='tokens_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='singletoken',
            name='expiry_date',
            field=django_jalali.db.models.jDateTimeField(editable=False, verbose_name='تاریخ و زمان انقضا'),
        ),
        migrations.AlterField(
            model_name='singletoken',
            name='is_used',
            field=models.BooleanField(default=False, editable=False, verbose_name='استفاده شده'),
        ),
    ]
